update: Add and update TypeScript and Unicorn rules.
Oriflame/lumos pull request #239
Opened 2021-01-18 14:58 UTC by jakubmazanec

2021-01-24 21:54 UTC, rajzik requested changes
Can you please split this PR to two, first change only order and then the rules, this is quite confusing to read.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/package.json
> +    "@typescript-eslint/eslint-plugin": "^4.14.0",
Please do not update dependencies when changing code

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/index.ts
> +    .toString()}`;
Why did you changed this?

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/base.ts
> +    'eslint-comments/no-aggregating-enable': 'error', // disallow a eslint-enable comment for multiple eslint-disable comments
Why is this enabled?

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/base.ts
> +    'eslint-comments/no-unused-enable': 'error', // disallow unused eslint-enable comments
This is already checked by eslint.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/base.ts
> +  plugins: ['import', 'react', 'react-hooks', 'eslint-comments'],
I don't really see advantage of this plugin TBH.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/base.ts
> +  plugins: ['import', 'react', 'react-hooks', 'eslint-comments'],
Also, it looks little bit deprecated as last release was more than a year ago.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    // not enabled in Airbnb
Why exactly did you change all leading character to lower case?

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'react/jsx-key': 'warn',
This should remaing error.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'react/jsx-handler-names': 'warn',
It would be great to have event handlers with some prefix.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'react/jsx-no-useless-fragment': 'warn',
This should remain error. Useless fragment adds complexity to the virtual dom that is not neccessary.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'unicorn/better-regex': 'warn', // improve regexes by making them shorter, consistent, and safer
This should remain error as it is autofixable.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'unicorn/consistent-function-scoping': 'warn', // move function definitions to the highest possible scope
This should remaing error. It is better for the parser when function can be declared in highest scope possible.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'unicorn/empty-brace-spaces': 'off', // enforce no spaces between braces
This is handled by prettier and can be removed.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'unicorn/filename-case': 'off', // enforce a case style for filenames
This is disabled by default, can be removed.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'unicorn/no-abusive-eslint-disable': 'warn', // enforce specifying rules to disable in eslint-disable comments
This handles most of the cases of the comments plugin.

2021-01-24 21:54 UTC, rajzik commented on packages/config-eslint/src/presets/next.ts
> +    'unicorn/prefer-default-parameters': 'off', // prefer default parameters over reassignment
This should be at least warning as param reassignment is an error.

2021-01-25 14:28 UTC, jakubmazanec commented on packages/config-eslint/package.json
> +    "@typescript-eslint/eslint-plugin": "^4.14.0",
Why not?

2021-01-25 22:19 UTC, rajzik commented on packages/config-eslint/package.json
> +    "@typescript-eslint/eslint-plugin": "^4.14.0",
dependencies should be changed separately.

2021-02-10 09:20 UTC, rajzik requested changes

2021-03-08 11:19 UTC, closed without merging