breaking: Revamp ESLint config.
Oriflame/lumos pull request #260
Opened 2021-02-01 22:24 UTC by jakubmazanec

Completely restructures ESLint config; adds additional plugins, removes
unnecessary presets and makes each rules explicitly defined.

2021-02-02 08:05 UTC, rajzik commented
Did you remove airbnb config?

2021-02-09 23:03 UTC, jakubmazanec commented
> 
> 
> Did you remove airbnb config?

Yes; I updated the first comment with additional explanation.

2021-02-10 09:38 UTC, rajzik commented
Which airbnb rules are obsolete?

2021-02-10 13:06 UTC, rajzik requested changes

2021-02-11 10:37 UTC, jakubmazanec commented
> 
> 
> Which airbnb rules are obsolete?

Everything that was moved to eslint-plugin-node (deprecatd in ESLint 7). I also found some rule that was deprecated in ESLint 4... But I don't remember which it was or where it actually came from (for the final comparison I used config generated by `--print-config` option of ESLint).

2021-02-11 10:40 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/prefer-includes': 'off', // prefer .includes() over .indexOf() when checking for existence or non-existence
Because this exists: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-includes.md

2021-02-11 10:43 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/prefer-default-parameters': 'off', // prefer default parameters over reassignment
I don't know, seems kind of pointless, doesn't it? We have https://eslint.org/docs/rules/no-param-reassign and https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md.

2021-02-11 10:44 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/no-nested-ternary': 'warn', // disallow nested ternary expressions
I never used them or encountered them, so I didn't thought this rule was that important. But sure, will fix.

2021-02-11 10:48 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/prefer-array-flat-map': 'warn', // prefer .flatMap(…) over .map(…).flat()
Warnings are fixable too, so I personaly don't take that into account when deciding whether a rule should be error or warning. And this particular rule is more "performance suggestion" kind of rule rather than "unacceptable style we don't want in our codebase".

2021-02-11 10:57 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/consistent-destructuring': 'warn', // use destructured variables over properties.
Fixed.

2021-02-11 10:57 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/import-index': 'warn', // enforce importing index files with .
Fixed.

2021-02-11 10:58 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/no-abusive-eslint-disable': 'off', // enforce specifying rules to disable in eslint-disable comments
But it serves different function. Anyway, which rules would you specify?

2021-02-11 11:02 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/no-array-push-push': 'off', // enforce combining multiple Array#push() into one call
Fixed.

2021-02-11 11:12 UTC, jakubmazanec commented on packages/config-eslint/src/rules/testing-library.ts
> +      files: [`*.test.{ts,tsx,js,jsx}`],
Probably forgot to add it... Fixed.

2021-02-11 11:12 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/self-closing-comp': 'warn', // prevent extra closing tags for components without children
Fixed.

2021-02-11 11:22 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/no-multi-comp': 'off', // prevent multiple component definition per file
I don't agree. There are situations when it would reduce our ability to orient in codebase, like when you have tightly coupled components, e.g. when there are two components and one is always child of the other one, like when you have some List and you create Item components so you can use props for passing parameters to a callback.

2021-02-11 11:23 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/no-find-dom-node': 'off', // prevent usage of findDOMNode
Fixed.

2021-02-11 11:26 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/no-array-index-key': 'warn', // prevent usage of Array index in keys
Hmm, I guess you're right; I thought there could be exemptions, but in that case rule disabling comment would still be required. Will fix.

2021-02-11 11:37 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/jsx-fragments': ['error', 'syntax'], // enforce shorthand or standard form for React fragments
🤦‍♂️ I changed it from element mode (like it was in @ori/eslint-config). I prefer element too, so should I change it back?

2021-02-11 11:39 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/jsx-curly-brace-presence': 'off', // disallow unnecessary JSX expressions when literals alone are sufficient or enfore JSX expressions on literals in JSX children or attributes
Fixed.

2021-02-11 11:43 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/jsx-child-element-spacing': 'off', // ensures inline tags are not rendered without spaces between them
Fixed.

2021-02-11 11:45 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/jsx-boolean-value': 'off', // enforce boolean attributes notation in JSX
Fixed.

2021-02-11 11:45 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +    'react/button-has-type': 'warn', // forbid "button" element without an explicit "type" attribute
Fixed.

2021-02-11 11:48 UTC, jakubmazanec commented on packages/config-eslint/src/rules/jest.ts
> +        'jest/no-if': 'off', // disallow conditional logic
Seemed to strict to me, but will fix (since I presume you think otherwise).

2021-02-11 11:48 UTC, jakubmazanec commented on packages/config-eslint/src/rules/jest.ts
> +        'jest/prefer-spy-on': 'warn', // suggest using jest.spyOn()
Fixed.

2021-02-11 11:50 UTC, jakubmazanec commented on packages/config-eslint/src/rules/eslint-comments.ts
> +import { ESLintConfig } from '@beemo/driver-eslint';
In what code? This or the FE wiki? In the former case I have little bit trouble genererating config for the lumos monorepo, in the latter the plugin wasn't included in @ori/eslint-config yet when I created the wiki generator.

2021-02-11 11:57 UTC, jakubmazanec commented on packages/config-eslint/src/rules/compat.ts
>  import { ESLintConfig } from '@beemo/driver-eslint';
It allows you to set polyfills, so I think it would be useful. But I guess we should still have completely specified browser list and stuff like that, so I will remove it from the extends list.

2021-02-11 12:01 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/media-has-caption': 'off', // enforces that <audio> and <video> elements must have a <track> for captions
It seems overly specific. Do we event use this component? Also, there is option to add custom components - do we have any?

2021-02-11 12:03 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/interactive-supports-focus': 'off', // enforce that elements with interactive handlers like onClick must be focusable
I don't know, it looks very complicated and prone to false positives... But I may be wrong in this case.

2021-02-11 12:07 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/img-redundant-alt': 'off', // enforce <img> alt prop does not contain the word "image", "picture", or "photo"
Seems too specific, you have to specify components (that's not a problem, I guess) and words - how does it work with our i18n solution?

2021-02-11 12:20 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/anchor-is-valid': 'off', // enforce all anchors are valid, navigable elements
Again, seems too complicated.

2021-02-11 12:34 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +import { ESLintConfig } from '@beemo/driver-eslint';
In general, I don't like presets with recommanded settings. Not using them avoids worrying about precedence issues due to import order, confusion about overriding/undoing settings (if you're overriding the recommendation, why even use it in the first place?), etc. It's better to be explicit, with each rule configured once (it's bad enough we have to deal with typescript plugin needing some ESLint rules to be disabled).

2021-02-12 10:08 UTC, rajzik commented on packages/config-eslint/src/rules/a11y.ts
> +import { ESLintConfig } from '@beemo/driver-eslint';
Have you made accessible web? I am not sure that either I or you, are someone who can tell what is best practice or not.

2021-02-12 14:16 UTC, rajzik commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/prefer-default-parameters': 'off', // prefer default parameters over reassignment
This rule doesn't have anything to do with preffer nullish coalescing. 
it is better to write
```ts
function foo(myVariable: string = '') {}
// instead of
function foo(myVariable?: string) {
  const test = getStuff(myVariable ?? '');
  const test2 = getStuff2(myVariable ?? '');
}
```

2021-02-12 14:17 UTC, rajzik commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/anchor-is-valid': 'off', // enforce all anchors are valid, navigable elements
What is complicated about it?

2021-02-12 14:18 UTC, rajzik commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/img-redundant-alt': 'off', // enforce <img> alt prop does not contain the word "image", "picture", or "photo"
I am not sure that you understand accessibility. Alts are quite crucial part for web readers.

2021-02-12 14:19 UTC, rajzik commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/interactive-supports-focus': 'off', // enforce that elements with interactive handlers like onClick must be focusable
When you have interactive elements, you should be able to use tab to navigate it and invoke it via the keyboard, that's why is this rule enabled.

2021-02-12 14:20 UTC, rajzik commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/media-has-caption': 'off', // enforces that <audio> and <video> elements must have a <track> for captions
One team was working on video player.

2021-02-15 00:39 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/prefer-default-parameters': 'off', // prefer default parameters over reassignment
I agree, but what I mean is that `no-param-reassign` already warns against
```js
function abc(foo) {
  foo = foo || 'bar';
}
```
but `unicorn/prefer-default-parameters` doesn't warn against your example:
```js
function foo(myVariable?: string) {
  const test = getStuff(myVariable ?? '');
  const test2 = getStuff2(myVariable ?? '');
}
```
It finally warns against:
```js
function foo(myVariable?: string) {
  const test = myVariable ?? '';
}
```
so I guess that's something that goes beyond what `no-param-reassign` does.

Will fix.

2021-02-15 00:46 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/img-redundant-alt': 'off', // enforce <img> alt prop does not contain the word "image", "picture", or "photo"
And I am not sure if you read what the rule actually does: "Enforce img alt attribute does not contain the word image, picture, or photo." And you have to specify components the rule will check, and what words are considered redundant. How does that help us? I am all for a11y rules, but they seem to have serious limitation how to automatically enforce them.

2021-02-15 01:00 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/interactive-supports-focus': 'off', // enforce that elements with interactive handlers like onClick must be focusable
I'm not arguing against the logic behind the rule, but whether it can be useful in actual application. But let's turn it on, we'll see.

2021-02-15 01:10 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/anchor-is-valid': 'off', // enforce all anchors are valid, navigable elements
Too much description for thing that is practically solved for us by using @ori-ui and stuff (I suppose we have separate components for links and buttons there). But I guess we can use it anyway; what are all link components that we use (e.i. from MUI, Next.js, etc.) - that needs to be specified for the rule to actually work.

2021-02-15 01:11 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/media-has-caption': 'off', // enforces that <audio> and <video> elements must have a <track> for captions
Ok then, will fix.

2021-02-15 15:41 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +import { ESLintConfig } from '@beemo/driver-eslint';
1) Best practices and recommended ruleset are two different things. 2) I think we are smart enough to decide for ourselves what's best for our use cases. 3) Explicit definition in single config is still the best. 4) A11y issues we most probably have in our apps will not be solved by using ESLint anyway.

2021-02-16 12:46 UTC, jakubmazanec commented on packages/config-eslint/src/rules/unicorn.ts
> +    'unicorn/better-regex': 'warn', // improve regexes by making them shorter, consistent, and safer
Same arguments as elsewhere... Autofixability should not be a factor in deciding rule severity.

2021-02-23 22:28 UTC, rajzik commented
> > Did you remove airbnb config?
> 
> Yes; I updated the first comment with additional explanation.

I have checked and they were like 6 deprecated rules from all configs, i don't think that we should change it entirely because of 6 rules.

2021-02-26 09:34 UTC, closed without merging

2021-02-26 09:36 UTC, rajzik commented
People already using this config as is and this change is way too big and also removes main config that we agreed upon, closing this PR.