feature!: Revamp ESLint config.
Oriflame/lumos pull request #392
Opened 2021-03-08 12:42 UTC by jakubmazanec

2021-03-25 09:46 UTC, rajzik requested changes

2021-03-29 08:27 UTC, rajzik commented on packages/config-eslint/package.json
> +    "eslint-plugin-compat": "^3.9.0",
Remove this as discussed.

2021-03-29 08:31 UTC, jakubmazanec commented on packages/config-eslint/src/rules/eslint.ts
> +    node: true,
🤷‍♂️ `node: true` was in previsou version, I just copied it.

Removed.

2021-03-29 08:33 UTC, jakubmazanec commented on packages/config-eslint/src/rules/react.ts
> +  plugins: ['eslint-plugin-react', 'eslint-plugin-react-hooks'],
I hate that ESLint allows using these shorthands... Package name is `eslint-plugin-whatever`, and that's what I will use, there's no need for magic names.

2021-03-29 08:33 UTC, jakubmazanec commented on packages/config-eslint/package.json
> +    "eslint-plugin-compat": "^3.9.0",
Fixed.

2021-03-29 08:33 UTC, jakubmazanec commented on packages/config-eslint/src/rules/eslint.ts
> +const config: ESLintConfig = {
Fixed.

2021-03-29 08:34 UTC, jakubmazanec commented on packages/config-eslint/src/rules/compat.ts
> +// TODO: Specify polyfills so it can be actually used.
Fixed.

2021-03-29 08:36 UTC, jakubmazanec commented on packages/config-eslint/src/rules/compat.ts
> +// TODO: Specify polyfills so it can be actually used.
But anyway, the compat plugin isn't about JS syntax compatibility, but about browser API compatibility and we should definitely be using it in future when we have finalized browserlist.

2021-03-29 08:44 UTC, jakubmazanec commented on packages/config-eslint/src/rules/node.ts
> +  env: {
Done.

2021-03-29 09:28 UTC, jakubmazanec commented on packages/config-eslint/src/rules/a11y.ts
> +const config: ESLintConfig = {
Can't do: 1) recommended has errors for everything which is not appropriate; 2) for some rules (e.g. `heading-has-content`) we need custom settings anyway; 3) Using recommended is not ideal in general, because it adds another layer of obscurity (it's basically the same thing as with the AirBnB preset - I want to have full control over what rules are enabled).

By the way, this is something I found during CR:
![jsx-a11y-anchor-is-valid](https://user-images.githubusercontent.com/4925556/112811167-12c24c80-907c-11eb-8bab-958fc9ff3171.png)

As this is typical behaviour of our coders, following best a11y practices shouldn't be done just by one ESLint plugin.

2021-03-31 08:58 UTC, rajzik requested changes
This is log from ori-ui: 
[error.log](https://github.com/Oriflame/lumos/files/6235249/error.log)
Did you even test the config?

2021-03-31 08:58 UTC, rajzik commented on packages/config-eslint/src/rules/a11y.ts
> +    'jsx-a11y/heading-has-content': ['warn', { components: 'Typography' }], // enforce heading (h1, h2, etc) elements contain accessible content
This is wrong components expect array.

2021-04-11 20:05 UTC, rajzik commented on packages/config-eslint/src/rules/testing-library.ts
> +const config: ESLintConfig = {
Right now, as of this PR is opened there was updated version of these plugins `promise`, `testing-library`, `unicorn`. can you please use recommended settings for a11y and testing library?

2021-04-20 06:55 UTC, rajzik commented
Please update plugin unicorn to new breaking change please.

2021-04-21 11:06 UTC, merged