update: Update rules.
Oriflame/lumos pull request #630
Opened 2021-06-10 17:10 UTC by jakubmazanec

2021-06-11 07:16 UTC, ecl1ps approved these changes

2021-06-14 07:19 UTC, rajzik requested changes

2021-06-14 07:19 UTC, rajzik commented on packages/config-eslint/src/rules/import.ts
> +        `**/__tests__/**/*.${JSX_EXTS_GROUP}`,
Please add `__tests__/**/*.${JSX_EXTS_GROUP}` as well.

2021-06-14 07:19 UTC, rajzik commented on packages/config-eslint/src/rules/typescript.ts
> +        `**/__tests__/**/*.${TJSX_EXTS_GROUP}`,
same as above.

2021-06-14 07:19 UTC, rajzik commented on packages/config-eslint/src/rules/typescript.ts
>        },
is it possible to add `_anything` to the function definition? Or how does it work right now? 
```tsx
(_context, theme) => theme.color;
```

2021-06-14 07:19 UTC, rajzik commented on packages/config-eslint/src/rules/typescript.ts
> -  '@typescript-eslint/no-unnecessary-condition': ['error', { allowConstantLoopConditions: true }], // prevents conditionals where the type is always truthy or always falsy -- false positive for some
Can you move these to some block with `todos` and `fixmes`?

2021-06-14 09:51 UTC, ecl1ps commented on packages/config-eslint/src/rules/import.ts
> +        `**/__tests__/**/*.${JSX_EXTS_GROUP}`,
I think that `**/__tests__/**/*.${JSX_EXTS_GROUP}` is superset of `__tests__/**/*.${JSX_EXTS_GROUP}`

2021-06-15 09:59 UTC, jakubmazanec commented on packages/config-eslint/src/rules/typescript.ts
> -  '@typescript-eslint/no-unnecessary-condition': ['error', { allowConstantLoopConditions: true }], // prevents conditionals where the type is always truthy or always falsy -- false positive for some
I don't know what you mean.

2021-06-15 10:04 UTC, jakubmazanec commented on packages/config-eslint/src/rules/typescript.ts
>        },
`(_, __, ___) => { /* ... */ }` etc. is allowed (the rule config works this way: if identifier matches a @typescript-eslint/naming-convention selector, in this case "variableLike", it is then checked against its regexp and if it matches the regexp as well, the identifier is ignored by the linter rule).
Anyway, just use `context` in your example (I think TypeScript config for unused parameters should be off, as it is useless).

2021-06-15 10:22 UTC, jakubmazanec commented on packages/config-eslint/src/rules/import.ts
> +        `**/__tests__/**/*.${JSX_EXTS_GROUP}`,
Anyway, done.

2021-06-15 10:22 UTC, jakubmazanec commented on packages/config-eslint/src/rules/typescript.ts
> +        `**/__tests__/**/*.${TJSX_EXTS_GROUP}`,
Done.

2021-06-16 09:47 UTC, jakubmazanec commented on packages/config-eslint/package.json
> +  "resolutions": {
Import plugin is broken and it doesn't that it will be fixed soon.

2021-06-18 12:30 UTC, rajzik approved these changes

2021-06-18 12:37 UTC, merged