update: Add Next.js ESLint plugin and update ESLint rules.
Oriflame/lumos pull request #727
Opened 2021-08-17 21:12 UTC by jakubmazanec

2021-08-18 10:32 UTC, rajzik commented on packages/config-eslint/README.md
>    next = false,
maybe change this to future? and create a breaking change?

2021-08-18 10:39 UTC, rajzik requested changes

2021-08-18 10:39 UTC, rajzik commented on packages/config-eslint/package.json
> +    "check-rules": "../../node_modules/.bin/ts-node tools/check-rules/index.ts"
Do you need this? Npm scripts have access to the bins.
```suggestion
    "check-rules": "ts-node tools/check-rules/index.ts"
```

2021-08-18 10:39 UTC, rajzik commented on packages/config-eslint/src/presets/base.ts
> +    'eslint:recommended',
Why did you remove airbnb?

2021-08-19 09:09 UTC, jakubmazanec commented on packages/config-eslint/src/presets/base.ts
> +    'eslint:recommended',
tl;dr - it is completely, absolutely useless for us and in the time since @oriflame/confgif-eslint last major release I've been proven right.

Same reasons as always:
1) No new release in 9 months (no minor release in 14 months, no major release in 2 years!!!)
2) They keep using deprecated rules, which complicate our config (we have to turn them off) 
3) My new update helper script (which shows new rules, so I don't have to comb through changelogs => significantly lower time to update our config) won't work with it (I would have to implement parsing "extends" fields).
4) We override a lot of its settings.
5) Its functionality is replaced by plugins' recommended configs.

2021-08-19 09:10 UTC, jakubmazanec commented on packages/config-eslint/package.json
> +    "check-rules": "../../node_modules/.bin/ts-node tools/check-rules/index.ts"
For some reason, in this repo, npm nor yarn add the "root" node_modules to PATH 🤷‍♂️ You can try it yourself, if you want, maybe it's just problem on my machine.

2021-08-22 17:14 UTC, rajzik commented on packages/config-eslint/src/presets/base.ts
> +    'eslint:recommended',
This is still against what we agreed upon. Do you really want to take care of this?

2021-08-23 08:55 UTC, jakubmazanec commented on packages/config-eslint/src/presets/base.ts
> +    'eslint:recommended',
I don't know what else to say. Using AirBnB config has always been mistake, brought no advantage and now it is actually slowing our work.

2021-08-23 12:35 UTC, jakubmazanec commented on packages/config-eslint/README.md
>    next = false,
Done. Hopefully I didn't miss something, I'm not very familiar with Lumos.

2021-08-23 15:54 UTC, jakubmazanec commented on packages/config-eslint/package.json
> +    "check-rules": "../../node_modules/.bin/ts-node tools/check-rules/index.ts"
Now it's working 🤦‍♂️ Weird.

2021-08-31 09:55 UTC, rajzik approved these changes

2021-08-31 10:07 UTC, merged