'unicorn/
Oriflame/lumos pull request #918
Opened 2021-12-29 12:59 UTC by jakubmazanec

2021-12-29 13:36 UTC, rajzik requested changes

2021-12-29 13:36 UTC, rajzik commented on packages/eslint-config/src/presets/base.ts
> -import jestRules from '../rules/jest-rules';
Why did you rename this? Rename of the name will result in error.

2021-12-29 13:36 UTC, rajzik commented on packages/eslint-config/src/rules/jest.ts
> +  'jest/prefer-lowercase-title': ['warn', { allowedPrefixes: [], ignoreTopLevelDescribe: true }], // enforce valid describe() callback
Disable this rule. Lowercase title doesn't make always sense.

2021-12-29 13:36 UTC, rajzik commented on packages/eslint-config/src/rules/typescript.ts
> +    { fixMixedExportsWithInlineTypeSpecifier: true },
Isn't { fixMixedExportsWithInlineTypeSpecifier: false } better?

2021-12-29 13:36 UTC, rajzik commented on packages/eslint-config/src/rules/typescript.ts
>    '@typescript-eslint/consistent-type-imports': 'off', // enforces consistent usage of type imports
Should we enable this when we have consistent type exports?

2021-12-29 13:36 UTC, rajzik commented on packages/eslint-config/src/rules/typescript.ts
> +  '@typescript-eslint/padding-line-between-statements': [
I am not sure if this isn't handled by prettier?

2021-12-29 13:36 UTC, rajzik commented on packages/eslint-config/tools/check-rules/tsconfig.json
> +    "rootDir": "../../",
Revert these changes pls.

2021-12-29 14:21 UTC, jakubmazanec commented on packages/eslint-config/tools/check-rules/tsconfig.json
> +    "rootDir": "../../",
What changes? `"module": "commonjs"` is needed.

2021-12-29 14:22 UTC, jakubmazanec commented on packages/eslint-config/src/rules/typescript.ts
> +  '@typescript-eslint/padding-line-between-statements': [
It isn't handled by Prettier; it's just extension of core ESLint rule `padding-line-between-statements`.

2021-12-29 14:26 UTC, jakubmazanec commented on packages/eslint-config/src/rules/typescript.ts
> +    { fixMixedExportsWithInlineTypeSpecifier: true },
I vote for `true`, because I think this is better:
```typescript
export { x, type T };
```
than
```typescript
export type { T };
export { x };
```

2021-12-29 14:26 UTC, jakubmazanec commented on packages/eslint-config/src/rules/typescript.ts
>    '@typescript-eslint/consistent-type-imports': 'off', // enforces consistent usage of type imports
Fixed.

2021-12-29 14:31 UTC, rajzik commented on packages/eslint-config/tools/check-rules/tsconfig.json
> +    "rootDir": "../../",
Why is it needed?

2021-12-29 14:40 UTC, jakubmazanec commented on packages/eslint-config/tools/check-rules/tsconfig.json
> +    "rootDir": "../../",
So I can run `ts-node tools/check-rules/index.ts` with no hassle - ESM are needlessly complicated in this case.

2021-12-29 20:52 UTC, rajzik commented on packages/eslint-config/src/rules/typescript.ts
> +    { fixMixedExportsWithInlineTypeSpecifier: true },
I would rather write

```ts
export type {
 a,
 b,
 c,
 d,
 e,
};
export { 
 test,
 asdf,
}
```

instead of writing type for every type export 

```ts
export {
  type a,
  type b,
  type c,
  type d,
  test,
  abcd
};
```

2021-12-30 10:54 UTC, rajzik approved these changes

2021-12-30 11:01 UTC, merged